PRN221_Project/Pages/Admin/CoursePage/AddCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.Admin.CoursePage
{
    public class AddCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public Course Course { get; set; }
        [BindProperty]
        public int profileId { get; set; }
        public List<Subject> listSub { get; set; }

        public AddCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            profileId = id;
            listSub = await _context.Subjects.Where(i => i.ProfileId == id).ToListAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var newCourse = new Course
            {
                Title = Course.Title,
                Description = Course.Description,
                NumberQuestion = Course.NumberQuestion,
                SubjectId = Course.SubjectId,
                Status = Course.Status,
                ProfileId = profileId,
            };
            _context.Courses.Add(newCourse);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/CoursePage/ListCourse", new { id = profileId });
        }
    }
}

PRN221_Project/Pages/Admin/CoursePage/DeleteCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.Admin.CoursePage
{
    public class DeleteCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        public DeleteCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int id, int pid)
        {
            var Course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            _context.Courses.Remove(Course);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/CoursePage/ListCourse", new { id = pid });
        }
    }
}

PRN221_Project/Pages/Admin/CoursePage/ListCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.Admin.CoursePage
{
    public class ListCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        public List<Course> ListCourse { get; set; }
        [BindProperty]
        public string? Keyword { get; set; }
        [BindProperty]
        public bool? Status { get; set; }
        public int PageIndex { get; set; } = 1;
        public int TotalPage { get; set; }
        public ListCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(string? keyword, bool? status, int pageIndex, int pagesize, int id)
        {
            Keyword = keyword;
            Status = status;
            if (pageIndex == 0) pageIndex = 1;
            PageIndex = pageIndex;
            pagesize = 4;
            var query = _context.Courses.AsQueryable();
            if (!string.IsNullOrEmpty(keyword))
            {
                query = query.Where(x => x.Title.ToLower().Contains(keyword.ToLower())
                                      || !string.IsNullOrEmpty(x.Description) && x.Description.ToLower().Contains(keyword.ToLower())
                );
            }
            if (status != null)
            {
                query = query.Where(x => x.Status == status);
            }

            if (id != 0)
            {
                query = query.Where(x => x.ProfileId == id);
            }

            ListCourse = await query.Include(i => i.Subject).Skip((pageIndex - 1) * pagesize)
                .Take(pagesize).OrderByDescending(i => i.CourseId).ToListAsync();

            TotalPage = (int)(Math.Ceiling(query.ToList().Count / (double)pagesize));
            return Page();
        }
    }
}

PRN221_Project/Pages/Admin/CoursePage/UpdateCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.Admin.CoursePage
{
    public class UpdateCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public Course Course { get; set; }

        [BindProperty]
        public int? profileId { get; set; }
        public List<Subject> listSub { get; set; }
        public UpdateCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int id, int pid)
        {
            Course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            profileId = pid;
            if (Course == null)
            {
                return NotFound();
            }
            listSub = await _context.Subjects.Where(i => i.ProfileId == pid).ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var s = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == Course.CourseId);
            s.Title = Course.Title;
            s.Description = Course.Description;
            s.Status = Course.Status;
            s.NumberQuestion = Course.NumberQuestion;
            s.SubjectId = Course.SubjectId;
            s.ProfileId = (int)profileId;
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/CoursePage/ListCourse", new { id = profileId });
        }
    }
}

PRN221_Project/Pages/CoursePage/AddCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.CoursePage
{
    public class AddCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public int CourseId { get; set; }
        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public int ProfileId { get; set; }
        [BindProperty]
        public int SubjectId { get; set; }
        [BindProperty]
        public int NumberQuestion { get; set; }
        public AddCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var course = new Course
            {
                CourseId = CourseId,
                Title = Title,
                Description = Description,
                ProfileId = ProfileId,
                SubjectId = SubjectId,
                NumberQuestion = NumberQuestion
            };
            _context.Courses.Add(course);
            await _context.SaveChangesAsync();
            return RedirectToPage("./ListCourse");
        }
    }
}

PRN221_Project/Pages/CoursePage/CourseDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Project.Models;
using System.Security.Claims;
using System;
using Microsoft.EntityFrameworkCore;

namespace PRN221_Project.Pages.CoursePage
{
    public class CourseDetailsModel : PageModel
    {
        private readonly PRN221Context _context;

        public Course Course { get; set; }
        public Subject Subject { get; set; }
        public CourseDetailsModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            Course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            Subject = await _context.Subjects.Include(i => i.Profile).FirstOrDefaultAsync(i => i.SubjectId == Course.SubjectId);
            if (Subject == null) throw new ArgumentException("Can not find subjet !");
            return Page();
        }

        public async Task<IActionResult> OnGetEnrolled(int id, int studentId)
        {
            var coure = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            Subject = await _context.Subjects.Include(i => i.Profile).FirstOrDefaultAsync(i => i.SubjectId == coure.SubjectId);
            Course = coure;
            if (coure == null) throw new ArgumentException("Can not find");
            coure.IsEnrolled += 1;
            await _context.SaveChangesAsync();

            var courePro = new ProfileCourse
            {
                CourseId = coure.CourseId,
                ProfileId = int.Parse(User.FindFirst(ClaimTypes.Sid)?.Value),
                TimeEnroll = DateTime.Now,
                Process = 0,
                NumberQuestion = 0,
            };
            await _context.ProfileCourses.AddAsync(courePro);
            await _context.SaveChangesAsync();

            ViewData["enroll"] = "yes";

            return Page();
        }
    }
}

PRN221_Project/Pages/CoursePage/DeleteCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.CoursePage
{
    public class DeleteCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        public DeleteCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int courId)
        {
            var question = await _context.Questions.FirstOrDefaultAsync(i => i.CourseId == courId);
            var course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == courId);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();


            return RedirectToPage("./ListCourse");
        }
    }
}

PRN221_Project/Pages/CoursePage/DetailCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;
using System.Security.Claims;

namespace PRN221_Project.Pages.CoursePage
{
    public class DetailCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        public Course Course { get; set; }
        public Subject Subject { get; set; }
        public DetailCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            Course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            Subject = await _context.Subjects.Include(i => i.Profile).FirstOrDefaultAsync(i => i.SubjectId == Course.SubjectId);
            if (Subject == null) throw new ArgumentException("Can not find subject !");

            var check = true;
            var uid = int.Parse(User.FindFirst(ClaimTypes.Sid)?.Value);
            var user = _context.ProfileCourses.Where(p => p.ProfileId == uid && p.CourseId == Course.CourseId).FirstOrDefault();
            if (user == null) check = false;
            else check = true;

            ViewData["check"] = check;

            return Page();
        }

        public async Task<IActionResult> OnGetEnrolled(int id, int studentId)
        {
            var course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            Subject = await _context.Subjects.Include(i => i.Profile).FirstOrDefaultAsync(i => i.SubjectId == course.SubjectId);
            Course = course;
            if (course == null) throw new ArgumentException("Can not find");
            course.IsEnrolled += 1;
            await _context.SaveChangesAsync();

            var courePro = new ProfileCourse
            {
                CourseId = course.CourseId,
                ProfileId = int.Parse(User.FindFirst(ClaimTypes.Sid)?.Value),
                TimeEnroll = DateTime.Now,
                Process = 0,
                NumberQuestion = 0,
            };
            await _context.ProfileCourses.AddAsync(courePro);
            await _context.SaveChangesAsync();

            ViewData["check"] = true;

            return Page();
        }

        public async Task<IActionResult> OnGetUnenrolled(int id, int pid)
        {
            var course = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == id);
            course.IsEnrolled -= 1;
            await _context.SaveChangesAsync();

            var courseProfile = await _context.ProfileCourses.FirstOrDefaultAsync(i => i.ProfileId == pid && i.CourseId == course.CourseId);
            _context.ProfileCourses.Remove(courseProfile);
            await _context.SaveChangesAsync();

            return RedirectToPage("ListEnrollCourse", new { id = pid });

        }
    }
}

PRN221_Project/Pages/CoursePage/ListCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.CoursePage
{
    public class ListCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public string? Search { get; set; }
        public List<Course> listCourse { get; set; }

        public ListCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(string? search)
        {
            Search = search;
            if (Search == null)
            {
                listCourse = await _context.Courses.ToListAsync();
            }
            else
            {
                listCourse = await _context.Courses.Where(i => !string.IsNullOrEmpty(i.Title) && i.Title.ToLower().Contains(search.ToLower().Trim())).ToListAsync();
            }
            return Page();
        }
    }
}

PRN221_Project/Pages/CoursePage/ListEnrollCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.CoursePage
{
    public class ListEnrollCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public string? Search { get; set; }
        public List<ProfileCourse> listProfileCourse { get; set; }
        public ListEnrollCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(string? search, int id)
        {
            listProfileCourse = await _context.ProfileCourses.Include(i => i.Profile).Include(i => i.Course).Where(i => i.ProfileId == id).ToListAsync();
            return Page();
        }
    }
}

PRN221_Project/Pages/CoursePage/UpdateCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;
using System;

namespace PRN221_Project.Pages.CoursePage
{
    public class UpdateCourseModel : PageModel
    {
        private readonly PRN221Context _context;

        [BindProperty]
        public Course Course { get; set; }

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; }
        public UpdateCourseModel(PRN221Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> OnGetAsync(int courId)
        {
            Course = await _context.Courses.Include(i => i.Subject).FirstOrDefaultAsync(i => i.CourseId == courId);
            if (Course == null) throw new ArgumentException("Can not find Course !");
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var c = await _context.Courses.FirstOrDefaultAsync(i => i.CourseId == Course.CourseId);
            c.Title = Course.Title;
            c.Description = Course.Description;
            c.NumberQuestion = Course.NumberQuestion;
            c.Status = Course.Status;
            await _context.SaveChangesAsync();
            return RedirectToPage("./ListCourse");
        }
    }
}

PRN221_Project/Pages/CoursePage/AddCourse.cshtml
@page
@model PRN221_Project.Pages.CoursePage.AddCourseModel
@{
}
<form method="post">
    <label>CourseId</label>
    <input asp-for="CourseId" type="text" placeholder="Course Id" /><br />
    <label>Subject Title</label>
    <input asp-for="Title" type="text" placeholder="Subject name" /><br />
    <label>Subject Description</label>
    <input asp-for="Description" type="text" placeholder="Subject Code" /><br />
    <label>Profile Id</label>
    <input asp-for="ProfileId" type="text" placeholder="Profile Id" /><br />
    <label>Subject SubjectId</label>
    <input asp-for="SubjectId" type="text" placeholder="Subject Id" /><br />
    <label>Subject NumberQuestion</label>
    <input asp-for="NumberQuestion" type="text" placeholder="NumberQuestion " /><br />
    <button type="submit">Save</button>
</form>

PRN221_Project/Pages/CoursePage/CourseDetails.cshtml
@page
@using System.Security.Claims;
@using PRN221_Project.Models;
@model PRN221_Project.Pages.CoursePage.CourseDetailsModel
@{
}
@{
    var context = new PRN221Context();
    var check = true;
    var id = int.Parse(User.FindFirst(ClaimTypes.Sid)?.Value);
    var user = context.ProfileCourses.Where(p => p.ProfileId == id && p.CourseId == Model.Course.CourseId).FirstOrDefault();
    if (user == null) check = false;
    else check = true;
}

<style>
    /* CSS */
    .button-5 {
        align-items: center;
        background-clip: padding-box;
        background-color: #fa6400;
        border: 1px solid transparent;
        border-radius: .25rem;
        box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
        box-sizing: border-box;
        color: #fff;
        cursor: pointer;
        display: inline-flex;
        font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 16px;
        font-weight: 600;
        justify-content: center;
        line-height: 1.25;
        margin: 0;
        min-height: 3rem;
        padding: calc(.875rem - 1px) calc(1.5rem - 1px);
        position: relative;
        text-decoration: none;
        transition: all 250ms;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        vertical-align: baseline;
        width: auto;
    }

        .button-5:hover,
        .button-5:focus {
            background-color: #fb8332;
            box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
        }

        .button-5:hover {
            transform: translateY(-1px);
        }

        .button-5:active {
            background-color: #c85000;
            box-shadow: rgba(0, 0, 0, .06) 0 2px 4px;
            transform: translateY(0);
        }
</style>

<div class="container-fluid page-header" style="margin-bottom: 90px;">
    <div class="container">
        <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
            <h3 class="display-4 text-white text-uppercase">Single</h3>
            <div class="d-inline-flex text-white">
                <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-angle-double-right pt-1 px-3"></i>
                <p class="m-0 text-uppercase">Single</p>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
<!-- Detail Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-8">
                <div class="mb-5">
                    <h6 class="text-primary mb-3">Jan 01, 2050</h6>
                    <h1 class="mb-5">@Model.Course.Title</h1>
                    <img class="img-fluid rounded w-100 mb-4" src="~/img/carousel-1.jpg" alt="Image">
                    <p>
                        @Model.Course.Description
                    </p>
                </div>
                @if (!check)
                {
                    <div class="text-center">
                        <!-- HTML !-->
                        <a asp-page="CourseDetails" asp-page-handler="Enrolled" asp-route-id="@Model.Course.CourseId" class="button-5" role="button">Enroll</a>
                    </div>
                }
                else
                {
                    <div class="text-center">
                        <!-- HTML !-->
                        <a asp-page="CourseDetails" asp-page-handler="Enrolled" asp-route-id="@Model.Course.CourseId" style="pointer-events: none;background-color:gray" class="button-5" role="button">Enroll</a>
                    </div>
                }


            </div>

            <div class="col-lg-4 mt-5 mt-lg-0">
                <!-- Author Bio -->
                <div class="d-flex flex-column text-center bg-dark rounded mb-5 py-5 px-4">
                    <img src="~/img/user.jpg" class="img-fluid rounded-circle mx-auto mb-3" style="width: 100px;">
                    <h3 class="text-primary mb-3">@Model.Subject.Profile.Name</h3>
                    <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h3>
                    <p class="text-white m-0">
                        @Model.Subject.Profile.Birthday
                    </p>
                </div>

                <!-- Search Form -->
                <div class="mb-5">
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-lg" placeholder="Keyword">
                            <div class="input-group-append">
                                <span class="input-group-text bg-transparent text-primary">
                                    <i class="fa fa-search"></i>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>

                <!-- Category List -->
                <div class="mb-5">
                    <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Subject</h3>
                    <ul class="list-group list-group-flush">
                        @if (check)
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a asp-page="QuestionPage/ListQuestion" asp-route-cid="@Model.Subject.SubjectId" class="text-decoration-none h6 m-0">@Model.Subject.Name</a>
                            </li>
                        }
                        else
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a asp-page="QuestionPage/ListQuestion" asp-route-cid="@Model.Subject.SubjectId" style="pointer-events: none" class="text-decoration-none h6 m-0">@Model.Subject.Name</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Detail End -->

PRN221_Project/Pages/CoursePage/DeleteCourse.cshtml
@page
@model PRN221_Project.Pages.CoursePage.DeleteCourseModel
@{
}

PRN221_Project/Pages/CoursePage/DetailCourse.cshtml
@page
@model PRN221_Project.Pages.CoursePage.DetailCourseModel
@{
    var check = ViewData["check"] as bool?;
}

<style>
    /* CSS */
    .button-5 {
        align-items: center;
        background-clip: padding-box;
        background-color: #fa6400;
        border: 1px solid transparent;
        border-radius: .25rem;
        box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
        box-sizing: border-box;
        color: #fff;
        cursor: pointer;
        display: inline-flex;
        font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 16px;
        font-weight: 600;
        justify-content: center;
        line-height: 1.25;
        margin: 0;
        min-height: 3rem;
        padding: calc(.875rem - 1px) calc(1.5rem - 1px);
        position: relative;
        text-decoration: none;
        transition: all 250ms;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        vertical-align: baseline;
        width: auto;
    }

        .button-5:hover,
        .button-5:focus {
            background-color: #fb8332;
            box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
        }

        .button-5:hover {
            transform: translateY(-1px);
        }

        .button-5:active {
            background-color: #c85000;
            box-shadow: rgba(0, 0, 0, .06) 0 2px 4px;
            transform: translateY(0);
        }
</style>

<div class="container-fluid page-header" style="margin-bottom: 90px;">
    <div class="container">
        <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
            <h3 class="display-4 text-white text-uppercase">Single</h3>
            <div class="d-inline-flex text-white">
                <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-angle-double-right pt-1 px-3"></i>
                <p class="m-0 text-uppercase">Single</p>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
<!-- Detail Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-8">
                <div class="mb-5">
                    <h6 class="text-primary mb-3">Jan 01, 2050</h6>
                    <h1 class="mb-5">@Model.Course.Title</h1>
                    <img class="img-fluid rounded w-100 mb-4" src="~/img/carousel-1.jpg" alt="Image">
                    <p>
                        @Model.Course.Description
                    </p>
                </div>
                @if (check == false)
                {
                    <div class="text-center">
                        <!-- HTML !-->
                        <a asp-page="DetailCourse" asp-page-handler="Enrolled" asp-route-id="@Model.Course.CourseId" class="button-5" role="button">Enroll</a>
                    </div>
                }
                else
                {
                    <div class="text-center">
                        <!-- HTML !-->
                        <a asp-page="DetailCourse" asp-page-handler="Enrolled" asp-route-id="@Model.Course.CourseId" style="pointer-events: none;background-color:gray" class="button-5" role="button">Enroll</a>
                    </div>
                }


            </div>

            <div class="col-lg-4 mt-5 mt-lg-0">
                <!-- Author Bio -->
                <div class="d-flex flex-column text-center bg-dark rounded mb-5 py-5 px-4">
                    <img src="~/img/user.jpg" class="img-fluid rounded-circle mx-auto mb-3" style="width: 100px;">
                    <h3 class="text-primary mb-3">@Model.Subject.Profile.Name</h3>
                    <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h3>
                    <p class="text-white m-0">
                        @Model.Subject.Profile.Birthday
                    </p>
                </div>

                @*<!-- Search Form -->
                <div class="mb-5">
                <form action="">
                <div class="input-group">
                <input type="text" class="form-control form-control-lg" placeholder="Keyword">
                <div class="input-group-append">
                <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
                </span>
                </div>
                </div>
                </form>
                </div>*@

                <!-- Category List -->
                <div class="mb-5">
                    @*<h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Subject</h3>*@
                    <ul class="list-group list-group-flush">
                        @if (check == true)
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a class="btn btn-danger" href="../QuestionPage/ListQuestion?cid=@Model.Course.CourseId" class="text-decoration-none h6 m-0">Learn Question</a>
                            </li>
                        }
                        else
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a class="btn btn-secondary" href="../QuestionPage/ListQuestion?cid=@Model.Course.CourseId" style="pointer-events: none" class="text-decoration-none h6 m-0">Learn Question</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Detail End -->

PRN221_Project/Pages/CoursePage/ListEnrollCourse.cshtml
@page
@using System.Security.Claims;
@model PRN221_Project.Pages.CoursePage.ListEnrollCourseModel
@{
}

<table class="table" style="margin-top: 100px;">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Course Name</th>
            <th scope="col">Time Enroll</th>
            @* <th scope="col">Process</th> *@
            @* <th scope="col">Number of Question</th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model.listProfileCourse)
        {
            <tr>
                <th scope="row">@item.Course.CourseId</th>
                <td><a asp-page="DetailCourse" asp-route-id="@item.Course.CourseId">@item.Course.Title</a></td>
                <td>@item.TimeEnroll</td>
                @* <td>@item.Process</td>
                <td>@item.NumberQuestion</td> *@
                <td><a asp-page="DetailCourse" asp-page-handler="Unenrolled" asp-route-pid="@User.FindFirst(ClaimTypes.Sid)?.Value" asp-route-id="@item.CourseId">Unenroll</a></td>
            </tr>
        }

    </tbody>
</table>